# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'History-Project-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for History-Project-ios
 pod 'RxAlamofire'
 pod 'Kingfisher'
 pod 'RxSwift'
 pod 'RxCocoa'
end
